# Generated by Django 4.0.5 on 2022-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Values', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(max_length=5)),
                ('Time', models.DateField(verbose_name='Date Event')),
            ],
        ),
    ]
