# Generated by Django 4.0.5 on 2022-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsumerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodels',
            name='unit',
        ),
    ]
