# Generated by Django 4.0.5 on 2022-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsumerApp', '0003_alter_devicemodels_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='Time',
            field=models.IntegerField(),
        ),
    ]
