# Generated by Django 4.0.5 on 2022-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Values', models.IntegerField()),
                ('Time', models.DateField(verbose_name='Date Event')),
            ],
        ),
    ]
